package zula.resources;

import java.util.ListResourceBundle;

public class Resource_mkd_MKD extends ListResourceBundle {



    private static final Object[][] CONTENTS = {
            {"LANGUAGE", "Јазик"},
            {"REMOTE HOST ADDRESS:", "Адреса на далечински домаќин:"},
            {"REMOTE HOST PORT:", "Порта за далечински домаќин::"},
            {"SUBMIT", "Поднесете"},
            {"LOGIN", "Логирај Се"},
            {"PASSWORD", "Лозинка"},
            {"REGISTER", "Регистрирајте се"},
            {"ARGUMENT", "Аргумент"},
            {"COMMAND", "Команда"},
            {"Visual style", "Визуелен стил"},
            {"Back to normal", "Врати се во нормала"},
            {"Impossible to get commands", "Невозможно е да се добијат команди"},
            {"Enter command!", "Внесете команда!"},
            {"There is no such command", "Не постои таква команда"},
            {"Error sending response", "Грешка при испраќање одговор"},
            {"Error while getting response", "Грешка при добивање одговор"},
            {"The Threat of Recursion!", "Заканата од рекурзија!"},
            {"File not found or no permissions", "Датотеката не е пронајдена или нема дозволи"},
            {"Wrong args", "Погрешни арги"},
                {"FIELD", "ПОЛЕ"},
            {"id", "id"},
            {"name", "име"},
            {"x", "х"},
            {"y", "у"},
            {"creationDate", "датум на производство"},
            {"age", "возраста"},
            {"wingspan", "распон на крилјата"},
            {"color", "боја"},
            {"type", "тип"},
            {"depth", "длабочина"},
            {"num. of tres.", "број. на дрвјата."},
            {"Number ot Treasures", "Број на богатства"},
            {"owner_id", "ИД на сопственикот"},
            {"value", "вредност"},
            {"REQUIREMENT", "БАРАЊЕ"},
            {"NOT NULL", "НЕ НУЛАТНИ"},
            {">=-23, double", ">=-23, двојно"},
            {"<=160, integer", "<=160, цел број"},
            {"long, >0", "долго, > 0"},
            {"float, >0", "плови, > 0"},
            {"may be null", "може да биде нула"},
            {"Float, may be null", "Плови, може да биде нула"},
            {"Double, may be null", "Двојно, може да биде нула"},
            {"CHECK THE CURRENCY OF THE DATA", "ПРОВЕРЕТЕ ЈА ВАЛУТАТА НА ПОДАТОЦИТЕ"},
            {"Delete", "Избриши"},
            {"It is not your dragon", "Тоа не е твој змеј("},
            {"OK", "OK"},
            {"Filter!", "Филтрирај!"},
            {"More than", "Повеќе од"},
            {"Less than", "Помалку од"},
            {"Equals", "Еднакви"},
            {"help", "помош"},
            {"info", "инфо"},
            {"show", "покажуваат"},
            {"update_id", "ажурирање id"},
            {"remove_by_id", "отстрани со ид"},
            {"clear", "јасно"},
            {"execute_script", "изврши скрипта"},
            {"exit", "излез"},
            {"remove_last", "отстранете го последното"},
            {"remove_lower", "отстрани пониски"},
            {"reorder", "пренарачување"},
            {"average_of_wingspan", "просечен распон на крилјата"},
            {"print_ascending", "печати растечки"},
            {"print_field_ascending_wingspan", "поле за печатење растечки"},
            {"add", "додадете"},
            {"No arg needed", "Не е потребен арг"},
            {"ID(int) needed", "Потребен е ID(int)."},
            {"Table is correct", "Табелата е точна"},
            {"Id must be a number!", "ИД мора да биде број!"},
            {"From a to z", "Од а до ш"},
            {"From z to a", "Од ш до a"},
            {"Sort!", "Подреди!"},
            {"Successful erasing!", "Успешно бришење!"},
            {"Nothing to delete", "Ништо да се избрише"},
            {"Successful execution!", "Успешно извршување!"},
            {"Impossible to add element", "Невозможно е да се додаде елемент"},
            {"Impossible to change data base", "Невозможно е да се смени базата на податоци"},
            {"There is no element with such id or you are not its creator", "Нема елемент со таков ид или вие не сте негов креатор"},
            {"Good buy!", "Добро купување!"},
            {"Successful authorization", "Успешно овластување"},
            {"Failed to login, please check the correctness of the entered data", "Не успеав да се најавите, проверете ја точноста на внесените податоци"},
            {"Successful registration", "Успешна регистрација"},
            {"Error registering, please try another username", "Грешка при регистрација, ве молиме обидете се со друго корисничко име"},
            {"Removal completed successfully!", "Отстранувањето заврши успешно!"},
            {"Either this id does not exist, or you are not its creator:(", "Или овој идентификатор не постои, или вие не сте неговиот креатор:("},
            {"Nothing to Remove", "Ништо да се отстрани"},
            {"There is no element with the given id", "Нема елемент со дадениот id"},
            {"Collection Shuffled", "Збирка измешана"},
            {"Object with this id does not exist or you do not have permissions", "Објектот со овој ID не постои или немате дозволи"},
            {"ERROR IN CONNECTION", "ГРЕШКА ВО ПОВРЗУВАЊЕ"},
            {"PORT MUST BE A NUMBER", "ПРИСТАНИЕТО МОРА ДА БИДЕ БРОЈ"}
    };



    @Override
    protected Object[][] getContents() {
        return CONTENTS;
    }
}
