package zula.resources;

import java.util.ListResourceBundle;

public class Resource_esp_ESP extends ListResourceBundle {



    private static final Object[][] CONTENTS = {
            {"LANGUAGE", "Idiome"},
            {"REMOTE HOST ADDRESS:", "Dirección de host remoto:"},
            {"REMOTE HOST PORT:", "Puerto de host remoto:"},
            {"SUBMIT", "Entregar"},
            {"LOGIN", "Acceso"},
            {"PASSWORD", "Clave"},
            {"REGISTER", "Registro"},
            {"ARGUMENT", "Argumento"},
            {"COMMAND", "Dominio"},
            {"Visual style", "Estilo visual"},
            {"Back to normal", "volver a la normalidad"},
            {"Impossible to get commands", "Imposible obtener comandos"},
            {"Enter command!", "Introduzca el comando!"},
            {"There is no such command", "No hay tal comando"},
            {"Error sending response", "Error al enviar respuesta"},
            {"Error while getting response", "Error al obtener respuesta"},
            {"The Threat of Recursion!", "¡La amenaza de la recursividad!"},
            {"File not found or no permissions", "Archivo no encontrado o sin permisos"},
            {"Wrong args", "Argumentos incorrectos"},
            {"FIELD", "CAMPO"},
            {"id", "id"},
            {"name", "nombre"},
            {"x", "х"},
            {"y", "у"},
            {"creationDate", "fecha de creación"},
            {"age", "años"},
            {"wingspan", "envergadura"},
            {"color", "color"},
            {"type", "escribe"},
            {"depth", "profundidad"},
            {"num. of tres.", "núm. de tes."},
            {"Number ot Treasures", "Número de tesoros"},
            {"owner_id", "id_propietario"},
            {"value", "valor"},
            {"REQUIREMENT", "REQUISITO"},
            {"NOT NULL", "NO NULO"},
            {">=-23, double", ">=-23, doble"},
            {"<=160, integer", "<= 160, entero"},
            {"long, >0", "largo, >0"},
            {"float, >0", "flotar, >0"},
            {"may be null", "Puede ser nula"},
            {"Float, may be null", "Flotador, puede ser nula"},
            {"Double, may be null", "Doble, puede ser nula"},
            {"CHECK THE CURRENCY OF THE DATA", "COMPRUEBE LA MONEDA DE LOS DATOS"},
            {"Delete", "Borrar"},
            {"It is not your dragon", "no es tu dragón("},
            {"OK", "OK"},
            {"Filter!", "¡Filtrar!"},
            {"More than", "Más que"},
            {"Less than", "Menos que"},
            {"Equals", "igual"},
            {"help", "ayuda"},
            {"info", "información"},
            {"show", "mostrar"},
            {"update_id", "actualizar_id"},
            {"remove_by_id", "eliminar_por_id"},
            {"clear", "claro"},
            {"execute_script", "ejecutar_script"},
            {"exit", "salida"},
            {"remove_last", "eliminar_último"},
            {"remove_lower", "quitar_inferior"},
            {"reorder", "reordenar"},
            {"average_of_wingspan", "promedio_de_envergadura"},
            {"print_ascending", "imprimir_ascendente"},
            {"print_field_ascending_wingspan", "campo de impresión envergadura"},
            {"add", "agregar"},
            {"No arg needed", "No se necesita argumento"},
            {"ID(int) needed", "ID (int) necesario"},
            {"Table is correct", "La tabla es correcta"},
            {"Id must be a number!", "¡El ID debe ser un número!"},
            {"From a to z", "De la A a la Z"},
            {"From z to a", "De z a a"},
            {"Sort!", "¡Clasificar!"},
            {"Successful erasing!", "¡Borrado exitoso!"},
            {"Nothing to delete", "Nada que borrar"},
            {"Successful execution!", "¡Ejecución exitosa!"},
            {"Impossible to add element", "Imposible añadir elemento"},
            {"Impossible to change data base", "Imposible cambiar la base de datos"},
            {"There is no element with such id or you are not its creator", "No existe ningún elemento con tal id o no eres su creador"},
            {"Good buy!", "¡Buena compra!"},
            {"Successful authorization", "Autorización exitosa"},
            {"Failed to login, please check the correctness of the entered data", "Error al iniciar sesión, verifique la exactitud de los datos ingresados"},
            {"Successful registration", "Registro exitoso"},
            {"Error registering, please try another username", "Error al registrarse, intente con otro nombre de usuario"},
            {"Removal completed successfully!", "¡Eliminación completada con éxito!"},
            {"Either this id does not exist, or you are not its creator:(", "O este id no existe, o no eres su creador :("},
            {"Nothing to Remove", "Nada que quitar"},
            {"There is no element with the given id", "No hay ningún elemento con el id dado"},
            {"Collection Shuffled", "Colección barajada"},
            {"Object with this id does not exist or you do not have permissions", "El objeto con esta identificación no existe o no tiene permisos"},
            {"ERROR IN CONNECTION", "ERROR EN LA CONEXIÓN" },
            {"PORT MUST BE A NUMBER", "EL PUERTO DEBE SER UN NÚMERO"}
    };

    @Override
    protected Object[][] getContents() {
        return CONTENTS;
    }
}
